# Generated by Django 5.0.3 on 2024-04-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_student_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='documents',
        ),
    ]
