# Generated by Django 5.0.3 on 2024-04-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='post',
            new_name='student',
        ),
    ]
