# Generated by Django 5.0.3 on 2024-04-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_rename_post_file_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='document/'),
        ),
    ]
